name: Book

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/**'

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: Book
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.40'
      - run: cd docs && mdbook build
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'docs/book'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
