name: Nix Flake

on:
  push:
    branches: ["main"]
    paths:
      - 'flake.nix'
      - 'flake.lock'
  pull_request:
    paths:
      - 'flake.nix'

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
      - 'flake.lock'
